name: Build Windows x64 only

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

defaults:
  run:
    shell: bash
    working-directory: src

env:
  CACHE_EPOCH: 1
  SCCACHE_CACHE_SIZE: 200M
  BUILD_TAG: v109.0.5414.74-2
  BUNDLE: naiveproxy-v109.0.5414.74-2-win-x64
  EXTRA_FLAGS: 'target_cpu="x64"'

jobs:
  win-x64:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          ref: v109.0.5414.74-2

      - name: Cache toolchains
        uses: actions/cache@v4
        with:
          path: |
            src/third_party/llvm-build/Release+Asserts/
            src/gn/
            ~/.cargo/bin/
            ~/bin/ninja.exe
          key: toolchains-win-x64-${{ hashFiles('CHROMIUM_VERSION') }}-v${{ env.CACHE_EPOCH }}

      - name: Cache PGO win64
        uses: actions/cache@v4
        with:
          path: src/chrome/build/pgo_profiles/chrome-win64-*
          key: pgo-win64-${{ hashFiles('CHROMIUM_VERSION') }}-v${{ env.CACHE_EPOCH }}

      - id: ccache-timestamp
        run: echo "SCCACHE_TIMESTAMP=$(date +%s)" >>$GITHUB_OUTPUT

      - name: Cache sccache files
        uses: actions/cache@v4
        with:
          path: ~/AppData/Local/Mozilla/sccache
          key: ccache-win-x64-${{ hashFiles('CHROMIUM_VERSION') }}-${{ steps.ccache-timestamp.outputs.SCCACHE_TIMESTAMP }}
          restore-keys: ccache-win-x64-${{ hashFiles('CHROMIUM_VERSION') }}-

      - name: Get clang
        run: ./get-clang.sh

      - name: Reset sccache stats
        run: ~/.cargo/bin/sccache -z || true

      - name: Build
        run: ./build.sh

      - name: Show sccache stats
        run: ~/.cargo/bin/sccache -s || true

      - name: Basic test
        run: ../tests/basic.sh out/Release/naive

      - name: Pack naiveproxy Windows x64
        run: |
          mkdir "$BUNDLE"
          if [ -f out/Release/naive.exe ]; then
            cp out/Release/naive.exe "$BUNDLE/naive.exe"
            openssl sha256 out/Release/naive.exe > sha256sum.txt
          else
            cp out/Release/naive "$BUNDLE/naive.exe"
            openssl sha256 out/Release/naive > sha256sum.txt
          fi
          cp config.json ../LICENSE ../USAGE.txt "$BUNDLE/"
          7z a "$BUNDLE.zip" "$BUNDLE"
          cat sha256sum.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: naiveproxy-v109.0.5414.74-2-win-x64
          path: |
            src/naiveproxy-v109.0.5414.74-2-win-x64.zip
            src/sha256sum.txt

      - name: Upload to release
        run: gh release upload "$BUILD_TAG" "$BUNDLE.zip" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
